C2DEVEL-14897: remove the legacy client and remove the use of boto
C2Devel/c2-client pull request #41
Opened 2024-07-26 11:04 UTC by gpilikin

2024-09-02 12:58 UTC, No-Rib requested changes

2024-09-02 12:58 UTC, No-Rib commented on c2client/utils.py
> +        if key == name:
Этот иф можно вынести из цикла, просто юзать .get(). Если вернулся None, то уже проходить по всем ключам

2024-09-02 12:58 UTC, No-Rib commented on c2client/utils.py
> +        if key == name:
Так-то и проход по ключам можно сделать один раз, построить маппинг

2024-09-02 13:53 UTC, pkulev requested changes

2024-09-13 08:02 UTC, No-Rib approved these changes

2024-10-23 13:21 UTC, pkulev approved these changes

2024-10-23 13:23 UTC, merged